### ISSUE TITLE
[SSL: UNSUPPORTED_PROTOCOL

### ISSUE THREAD

**Issue by aaxxtt** [zigoo0/webpwn3r#11]
[!] Scan URL or List of URLs? [1/2]: 1
 [!] Enter the URL: https://localhost/index.php?id=12
 
 [!] Fingerprinting the backend Technologies.
Traceback (most recent call last):
  File "scan.py", line 63, in <module>
    urls_or_list()
  File "scan.py", line 38, in urls_or_list
    rce_func(url)
  File "/home/sec/tools/web/vulnz.py", line 50, in rce_func
    headers_reader(url)
  File "/home/sec/tools/web/headers.py", line 33, in headers_reader
    opener = urllib.urlopen(url)
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 215, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 445, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 894, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 856, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1303, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:727)

what is this problem? im used tools in kali so can fix this problem?

**Comment by zigoo0** [comment]
Looks like SSL doesn't work on your localhost? try it with http:// instead of https:// and let me know how it goes.
